import { promises as fs, createReadStream } from 'node:fs';
import path from 'node:path';
import env from '../../../config/env.js';

/**
 * Local disk storage for development and small deployments.
 *
 * Files live outside any web root and are only ever served through the API, so
 * access control is applied on every read. Nothing here is reachable by URL
 * guessing.
 */

const root = path.resolve(env.STORAGE_LOCAL_PATH);

/**
 * Storage keys are generated by the service, never derived from a filename,
 * but this refuses to resolve outside the root regardless — a traversal bug
 * upstream should not become arbitrary file access.
 */
function resolveSafely(key) {
  const full = path.resolve(root, key);
  if (full !== root && !full.startsWith(root + path.sep)) {
    throw new Error('Refusing to resolve a storage key outside the storage root');
  }
  return full;
}

export const localDriver = {
  name: 'local',

  async put(key, buffer) {
    const full = resolveSafely(key);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, buffer);
    return { key };
  },

  async stream(key) {
    const full = resolveSafely(key);
    await fs.access(full);
    return createReadStream(full);
  },

  async buffer(key) {
    return fs.readFile(resolveSafely(key));
  },

  async remove(key) {
    try {
      await fs.unlink(resolveSafely(key));
    } catch (err) {
      // Already gone is the desired end state.
      if (err.code !== 'ENOENT') throw err;
    }
  },

  /**
   * Local storage has no signed URLs — the API streams the bytes itself.
   * Returning null tells the caller to use the download endpoint instead.
   */
  async signedUrl() {
    return null;
  },
};

export default localDriver;
